name: "Code Analysis"

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

permissions:
  contents: read

env:
  GO: "1.24"

jobs:
  UnitTests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2 # immutable action

      - name: Install Go
        uses: actions/setup-go@v5.5.0 # immutable action
        with:
          go-version: ${{ env.GO }}

      - name: Run Unit Tests
        run: go test -race -cover -coverprofile=coverage.out -covermode=atomic

      - name: Codecov
        uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24 # v5.4.3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}


  GolangCI-Lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2 # immutable action

      - name: Install Go
        uses: actions/setup-go@v5.5.0 # immutable action
        with:
          go-version: ${{ env.GO }}

      - name: Run GolangCi-Lint
        uses: golangci/golangci-lint-action@2226d7cb06a077cd73e56eedd38eecad18e5d837 # v6.5.0
